// <auto-generated />
namespace MoveMe.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class take2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(take2));
        
        string IMigrationMetadata.Id
        {
            get { return "201704191709360_take2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
